#!/usr/bin/env node
/**
 * render-fields.js — merge extracted facts + human notes into one Markdown page per form.
 *
 * READ-ONLY against the snapshot. Writes only to review/fields/.
 *
 *   review/fields/<Template>.extracted.json   machine facts   (regenerate freely)
 *   review/fields/<Template>.notes.json       human notes     (hand-authored, never overwritten)
 *   review/fields/<FORM_KEY>.md               the merged page (regenerate freely)
 *
 * Usage: node review/tools/render-fields.js
 */

'use strict';
const fs = require('fs');
const path = require('path');

const DIR = path.resolve(__dirname, '..', 'fields');

const TEMPLATES = ['InitialRequest', 'TerminationRequest', 'PositionSiteChangeRequest'];

const SUBMIT_STYLE_TEXT = {
  'explicit-map': 'Explicit map — the page builds a named object, so **only listed controls reach the server**. A new control is not submitted until it is added to that object.',
  'passthrough': 'Pass-through — `new FormData(form)` is iterated into an object, so **every named control is submitted under its own name**. Multi-values are comma-joined.',
  'passthrough-dom': 'Pass-through (DOM sweep) — the page walks its inputs, selects, checkboxes and radios and writes `obj[el.name] = el.value`, so **every named control is submitted under its own name**.',
  'unknown': 'Not determined automatically — check the submit handler.',
};

/** The registry, for the step instances each form is used by. */
function loadRegistry() {
  const p = path.join(DIR, '..', 'index.json');
  return fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, 'utf8')) : { stepInstances: {}, workflows: {} };
}

/**
 * Where this form is used as a step. A form is a reusable step component: the same form in two
 * workflows is two step instances, each with its own entry condition, actor and effects, and each
 * reviewed separately.
 */
function stepUsage(reg, formKey) {
  return Object.entries(reg.stepInstances || {})
    .filter(([k, v]) => k !== '$comment' && v && v.form === formKey)
    .map(([k, v]) => ({ key: k, ...v }))
    .sort((a, b) => String(a.workflow).localeCompare(String(b.workflow)) || a.ordinal - b.ordinal);
}

function loadNotes(tpl) {
  const p = path.join(DIR, `${tpl}.notes.json`);
  if (!fs.existsSync(p)) return { fields: {} };
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

function esc(s) {
  return String(s == null ? '' : s).replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim();
}

/** Human-readable "shown when" for one field in one form. */
function shownWhen(f, formKey) {
  const av = f.availability[formKey];
  if (!av.visible) return `**hidden** — ${esc((av.reason || []).join('; '))}`;
  const bits = [];
  if (f.wrapper) {
    const rule = f.showHideRules && f.showHideRules[0];
    bits.push(rule && rule.handler
      ? `\`#${f.wrapper}\` is open (\`${esc(rule.handler)}\`)`
      : `\`#${f.wrapper}\` is open`);
  }
  if (av.disabled) bits.push('disabled in this mode');
  return bits.length ? bits.join('; ') : 'always';
}

function renderForm(tplData, form, notes, reg) {
  const fields = Object.values(tplData.fields);
  const visible = fields.filter(f => f.availability[form.key].visible);
  const hidden = fields.filter(f => !f.availability[form.key].visible);
  const req = visible.filter(f => f.availability[form.key].requiredEffective);

  const out = [];
  out.push(`# ${form.key} — ${form.label}`);
  out.push('');
  const base = tplData.template.replace(/\.html$/, '');
  out.push('> Generated by `review/tools/render-fields.js` from `' + base + '.extracted.json` +');
  out.push('> `' + base + '.notes.json`. Do not hand-edit this file — edit the notes and re-render.');
  out.push('> Descriptive only. It records what the form does, never whether that is correct or');
  out.push('> intended — that is the maintainer\'s call, made during review of each flow.');
  out.push('');
  out.push('| | |');
  out.push('|---|---|');
  out.push(`| **Route** | \`?form=${(form.route || '').replace(/^ROUTE_/, '').toLowerCase()}\` (\`${form.route}\`) |`);
  out.push(`| **Template** | \`${tplData.template}\` |`);
  out.push(`| **Mode** | \`${form.mode}\`${form.baseMode ? ` (baseMode \`${form.baseMode}\`)` : ''} |`);
  out.push(`| **Fields visible** | ${visible.length} of ${fields.length} defined |`);
  out.push(`| **Required here** | ${req.length} |`);
  out.push(`| **Submit contract** | ${SUBMIT_STYLE_TEXT[tplData.submitStyle] || tplData.submitStyle} |`);
  out.push('');

  if (tplData.sharedTemplate) {
    const others = tplData.servesForms.filter(f => f.key !== form.key).map(f => `\`${f.key}\``).join(', ');
    out.push(`> **Shared template.** \`${tplData.template}\` also serves ${others}. One template, one`);
    out.push('> definition per field. The maintainer states this sharing is intended, so a field is only');
    out.push('> edited once. Each mode is still a');
    out.push('> distinct form in use, with its own route, audience and visible/required set. **An edit to');
    out.push('> any field below lands on every mode listed here.**');
    out.push('');
    if (form.variantNote) { out.push(`> **Variant.** ${form.variantNote}`); out.push(''); }
  }

  // Where this form is used as a step. Each use is reviewed on its own.
  const uses = stepUsage(reg, form.key);
  if (uses.length) {
    out.push('## Used as a step in');
    out.push('');
    out.push('A form is a reusable step component. The same form in two workflows is two step');
    out.push('instances — different entry condition, actor and effects — and each is reviewed');
    out.push('separately as part of its own flow.');
    out.push('');
    out.push('| Step instance | Workflow | # | Actor | Entry condition | Sets step to |');
    out.push('|---|---|:--:|---|---|---|');
    uses.forEach(u => {
      const wf = (reg.workflows || {})[u.workflow] || {};
      out.push(`| \`${u.key}\` | ${esc(wf.label || u.workflow)} | ${u.ordinal} | ${esc(u.actor)} | ${esc(u.entryCondition)} | ${esc(u.setsStep)} |`);
    });
    out.push('');
    uses.filter(u => u.note).forEach(u => { out.push(`- \`${u.key}\` — ${esc(u.note)}`); });
    if (uses.some(u => u.note)) out.push('');
    uses.filter(u => u.branches).forEach(u => { out.push(`- \`${u.key}\` branches: ${esc(u.branches)}`); });
    if (uses.some(u => u.branches)) out.push('');
  }

  // Fields grouped by the section heading the user sees.
  const sections = [];
  visible.forEach(f => {
    const s = f.section || '(no section — built at runtime)';
    let bucket = sections.find(x => x.name === s);
    if (!bucket) sections.push((bucket = { name: s, fields: [] }));
    bucket.fields.push(f);
  });

  out.push('## Fields');
  out.push('');
  sections.forEach(sec => {
    out.push(`### ${sec.name}`);
    out.push('');
    out.push('| Label | Control | Type | Req | Shown when | Effect |');
    out.push('|---|---|---|:--:|---|---|');
    sec.fields.forEach(f => {
      const n = (notes.fields || {})[f.control] || {};
      const av = f.availability[form.key];
      // A radio/checkbox group's scraped label is its FIRST option, which reads wrong as a group
      // name — so a notes label always wins for grouped controls.
      const grouped = ['radio', 'checkbox'].includes(f.type) && f.options.length > 1;
      const label = n.label || (grouped ? `\`${f.control}\`` : (f.label || '—'));
      const opts = grouped
        ? ' <br><sub>' + f.options.map(o => '`' + esc(o.value || '(blank)') + '`').join(' · ') + '</sub>'
        : '';
      const typeCell = f.origin === 'dynamic' ? `${f.type} *(built at load)*` : f.type;
      const effect = n.effect || (n.purpose ? n.purpose : '_not yet documented_');
      out.push(`| ${esc(label)}${opts} | \`${f.control}\` | ${typeCell} | ${av.requiredEffective ? '●' : ''} | ${shownWhen(f, form.key)} | ${esc(effect)} |`);
    });
    out.push('');
  });

  if (hidden.length) {
    out.push('## Not shown in this mode');
    out.push('');
    out.push('| Control | Why |');
    out.push('|---|---|');
    hidden.forEach(f => out.push(`| \`${f.control}\` | ${esc((f.availability[form.key].reason || []).join('; '))} |`));
    out.push('');
  }

  const notSubmitted = visible.filter(f => !f.submitted);
  if (notSubmitted.length) {
    out.push('## Visible but not submitted');
    out.push('');
    out.push('Present on the page, not included in the payload the handler receives.');
    out.push('');
    notSubmitted.forEach(f => out.push(`- \`${f.control}\`${f.label ? ` — ${esc(f.label)}` : ''}`));
    out.push('');
  }

  const dyn = visible.filter(f => f.origin === 'dynamic');
  if (dyn.length) {
    out.push('## Built at load time');
    out.push('');
    out.push('These have no markup — the page renders them from reference data, so they are invisible to');
    out.push('a markup-only read of the template.');
    out.push('');
    out.push('| Control | Container | Built by | From |');
    out.push('|---|---|---|---|');
    dyn.forEach(f => out.push(`| \`${f.control}\` | \`#${f.wrapper}\` | \`${f.builtBy}\` | \`${esc(f.builtFrom)}\` |`));
    out.push('');
  }

  const pending = visible.filter(f => !((notes.fields || {})[f.control] || {}).effect).length;
  out.push('---');
  out.push('');
  out.push(`_Effects documented: ${visible.length - pending}/${visible.length}. Snapshot ${tplData.extractedAt}._`);
  out.push('');
  return out.join('\n');
}

function main() {
  const reg = loadRegistry();
  let wrote = 0;
  TEMPLATES.forEach(tpl => {
    const p = path.join(DIR, `${tpl}.extracted.json`);
    if (!fs.existsSync(p)) { console.error(`missing ${tpl}.extracted.json — run extract-fields.js first`); return; }
    const data = JSON.parse(fs.readFileSync(p, 'utf8'));
    const notes = loadNotes(tpl);
    data.servesForms.forEach(form => {
      const md = renderForm(data, form, notes, reg);
      fs.writeFileSync(path.join(DIR, `${form.key}.md`), md);
      console.log(`wrote review/fields/${form.key}.md`);
      wrote++;
    });
  });
  console.log(`${wrote} form pages rendered.`);
}

main();
